version: '3.8'
services:
  web:
    image: monnginxpersonnalise
    container_name: nginx_web
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - my_custom_network

  database:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: docker-devops
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_custom_network
    ports:
      - "5432:5432"

volumes:
  postgres_data:

networks:
  my_custom_network:
