version: '3.8'
services:
  web:
    image: nginx
    container_name: nginx_web
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./html:/usr/share/nginx/html

  database:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docker-devops
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
