version: '3.8'
services:
  web:
    image: nginx
    container_name: nginx_web
    ports:
      - "${NGINX_PORT}:80"
  database:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docker-devops
    ports:
      - "5432:5432"
